apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000  # Grafana's default port
  type: ClusterIP  # Default to ClusterIP if not specified
