apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel'
              static_configs:
                - targets: ['localhost:9090']

    processors:
      batch:

    exporters:
      jaeger:
        endpoint: "http://jaeger:14250"  # 14250 is the default Jaeger gRPC port
        insecure: true
      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger, logging]
        metrics:
          receivers: [prometheus]
          exporters: [prometheus]
