apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel'
              static_configs:
                - targets: ['localhost:9090']

    processors:
      batch:

    exporters:
      jaeger:
        endpoint: "http://jaeger:14250"
        insecure: true
      prometheus:
        endpoint: "0.0.0.0:8888"

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [batch]
          exporters: [jaeger]
        metrics:
          receivers: [prometheus]
          exporters: [prometheus]
