apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 16686  # UI
            - containerPort: 14250  # OTLP gRPC (correct)
            - containerPort: 4317  # OTLP
            - containerPort: 4318  # OTLP HTTP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 30
            timeoutSeconds: 10
