FROM python:3.9-slim

WORKDIR /app
COPY hash_service.py /app

# Install required dependencies
RUN pip install --no-cache-dir \
    flask \
    prometheus-client \
    opentelemetry-sdk \
    opentelemetry-instrumentation-flask \
    opentelemetry-exporter-jaeger \
    opentelemetry-exporter-otlp \
    werkzeug

CMD ["python", "/app/hash_service.py"]
