apiVersion: apps/v1
kind: Deployment
metadata:
  name: length-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: length-service
  template:
    metadata:
      labels:
        app: length-service
    spec:
      containers:
        - name: length-service
          image: <your-registry>/length-service:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
