apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s  # Adjust as needed

    scrape_configs:
      - job_name: "hash-service"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["hash-service:8080"]

      - job_name: "length-service"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["length-service:8081"]
