replicaCount: 1

image:
  repository: jaegertracing/all-in-one
  tag: 1.53.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 16686

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

env:
  - name: COLLECTOR_ZIPKIN_HTTP_PORT
    value: "9411"
  - name: METRICS_STORAGE_TYPE
    value: "prometheus"
  - name: MEMORY_MAX_TRACES
    value: "5000"
