# values.yaml

agent:
  enabled: true
  ports:
    - port: 5775
    - port: 5778
    - port: 6831
    - port: 6832

collector:
  replicas: 1
  image:
    name: jaegertracing/jaeger-collector
    tag: 1.27.0

query:
  replicas: 1
  image:
    name: jaegertracing/jaeger-query
    tag: 1.27.0
  service:
    type: LoadBalancer

storage:
  type: memory
  memory:
    max-traces: 500000

