FROM python:3.9-slim

WORKDIR /app
COPY length_service.py /app

# Install required dependencies
RUN pip install --no-cache-dir \
    flask \
    prometheus-client \
    opentelemetry-sdk \
    opentelemetry-instrumentation-flask \
    opentelemetry-exporter-jaeger \
    werkzeug \
    gunicorn \
    opentelemetry-exporter-otlp \
    gunicorn  # Added Gunicorn for WSGI support

    CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8081", "length_service:app"]
